# -*- coding: utf-8 -*-
"""Calculadora Básica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5iMqmpWKHbziFKkatL-mWI0itfNfTSo

# Calculadora Básica Python
"""

# calculadora.py

def mostrar_menu():
    print("\n--- Calculadora Básica ---")
    print("1. Sumar")
    print("2. Restar")
    print("3. Multiplicar")
    print("4. Dividir")
    print("5. Salir")

def pedir_numero(mensaje):
    while True:
        try:
            return float(input(mensaje))
        except ValueError:
            print("❌ Error: Ingresa un número válido.")

def calculadora():
    while True:
        mostrar_menu()
        opcion = input("Selecciona una opción (1-5): ")

        if opcion == "5":
            print("👋 Gracias por usar la calculadora.")
            break

        if opcion not in ["1", "2", "3", "4"]:
            print("❌ Opción inválida. Intenta de nuevo.")
            continue

        num1 = pedir_numero("Ingresa el primer número: ")
        num2 = pedir_numero("Ingresa el segundo número: ")

        if opcion == "1":
            resultado = num1 + num2
            print(f"✅ Resultado: {num1} + {num2} = {resultado}")
        elif opcion == "2":
            resultado = num1 - num2
            print(f"✅ Resultado: {num1} - {num2} = {resultado}")
        elif opcion == "3":
            resultado = num1 * num2
            print(f"✅ Resultado: {num1} * {num2} = {resultado}")
        elif opcion == "4":
            if num2 == 0:
                print("❌ Error: No se puede dividir entre cero.")
            else:
                resultado = num1 / num2
                print(f"✅ Resultado: {num1} / {num2} = {resultado}")

if __name__ == "__main__":
    calculadora()